name: pyrosm_env
channels:
 - conda-forge
dependencies:
 - python=3.9
 - pyrosm
 - cykhash
 - pygeos=0.10
 - pip:
     - geotiler
 - numpy
 - matplotlib
 - Pillow
 - pandas
 - scipy
 - pathlib
 - scikit-learn
 - pytorch
 - pytorch-lightning
 - torchvision
 - shapely
